# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b0c92b0f2899861abf484a9671738f0c96438e9991c2f86a13172008859572386578e9e1225f66d6c25a2a685ee38fe102dea0b9bd37eaf80e2e720f7318862

test:
  secret_key_base: 3d6a2bb3bd5a3db8e99b5e5911e03c48867125835382f08a8e1e5c8f1faf8f461ad02b23bb70571f2c6b4887fbb3e7aa1da94e40e5785b84fe52ec11cfabab4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
